### ISSUE TITLE
Database name should not be specified

### ISSUE THREAD

**Issue by GIANTCRAB** [Arkarr/TF2-PowerShop#1]
Hello, 

Firstly, thank you once again for this fantastic plugin. I've encountered some issues with the MySQL part and so did some others. So I took a look at the source code and found out why this was happening.

The reason was because the database name was specified. Let's take a look at Line 37: https://github.com/Arkarr/TF2-PowerShop/blob/master/TF2PowerShop.sp#L37

```sourcepawn
#define QUERY_CREATE_T_CLIENTS		"CREATE TABLE IF NOT EXISTS `PowerShop`.`t_client` (`client_steamid64` VARCHAR(50) NOT NULL,`client_credits` INT(11) NOT NULL,`client_name` VARCHAR(50) NOT NULL,PRIMARY KEY (`client_steamid64`)) ENGINE = InnoDB DEFAULT CHARACTER SET = latin1;"
```

The database name was forcefully set to `PowerShop`. In my case, my database name was not `PowerShop` and thus, the creation failed. My proposed fix is to remove the inclusion of database name and change it to something like this instead:

```sourcepawn
#define QUERY_CREATE_T_CLIENTS		"CREATE TABLE IF NOT EXISTS `t_client` (`client_steamid64` VARCHAR(50) NOT NULL,`client_credits` INT(11) NOT NULL,`client_name` VARCHAR(50) NOT NULL,PRIMARY KEY (`client_steamid64`)) ENGINE = InnoDB DEFAULT CHARACTER SET = latin1;"
```

If you would like, I could also do a Pull Request. However, I'm not good at SourcePawn, I only know SQL well. 

Thank you.

**Comment by Arkarr** [comment]
I'll look at it more in details, but if I made it this way, it was because there was two t.client fields from two different table.

**Comment by GIANTCRAB** [comment]
>it was because there was two t.client fields from two different table.

Two different tables? Meaning?

Removal would not cause any breaking changes either because the code written was consistent -- all the queries had the database name set to `PowerShop`. I can test it too and see if it breaks anything.

**Comment by malomodo** [comment]
I ran into the same problem..when I create database my host automatically sets a prefix which I can not change.

**Comment by malomodo** [comment]
I am getting almost same issue. When I create database it adds a prefix which I can't change...so like xxxx_PowerShop.

Getting this:  TF2PowerShop.smx ([TF2] Power Shop): Database failure: SELECT command denied to user 'xxxxxx'@'66.xx.xx.xx' for table 't_clientupgrade'

**Comment by Arkarr** [comment]
Sorry for being inactive those last months. I'll fix that tomorrow / tonight

**Comment by malomodo** [comment]
OK cheers mate.

**Comment by Arkarr** [comment]
Issue reported. I'll check that later, since I want to focus on my steambot.

**Comment by malomodo** [comment]
@GIANTCRAB Hey there. Was just curious if you have a working fix for this that you would like to share? I have tried a few things and compiled but to no luck. Cheers.

**Comment by Arkarr** [comment]
Fixed.
