### ISSUE TITLE
Deadringer deaths award points to killer

### ISSUE THREAD

**Issue by GIANTCRAB** [Arkarr/TF2-PowerShop#2]
Hello, 

It seems like Deadringer deaths are not detected with the `TF_DEATHFLAG_DEADRINGER` death flag and the killer is still awarded points.

Could you fix this please? Thanks

**Comment by Arkarr** [comment]
I believe it's fixed. Also your problem was only for team kill, I guess. Since I checked the deathringer event for normal kills.
